// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Used to configure a probe to a controller
type ProbeSettings struct {
	// The address of the probe to add to a controller
	Address *string `json:"address"`
	// The name of the controller to add the probe to.
	Name *string `json:"name"`
}
